sudo: require
services:
  - docker

before_install:
  - docker build -t godlzr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run godlzr/react-test npm test -- --coverage

after_success:
  - docker build -t godlzr/multi-client ./client
  - docker build -t godlzr/multi-nginx ./nginx
  - docker build -t godlzr/multi-server ./server
  - docker build -t godlzr/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push godlzr/multi-client
  - docker push godlzr/multi-nginx
  - docker push godlzr/multi-server
  - docker push godlzr/multi-worker
